using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Charlotte.Common;

namespace Charlotte
{
	public class ResourceSE
	{
		//public DDSE Dummy = new DDSE("Dummy.mp3");

		public DDSE Coin01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin01.mp3");
		public DDSE Coin02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin02.mp3");
		public DDSE Coin03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin03.mp3");
		public DDSE Coin04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin04.mp3");
		public DDSE Coin05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin05.mp3");
		public DDSE Coin06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin06.mp3");
		public DDSE Coin07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin07.mp3");
		public DDSE Coin08 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\coin08.mp3");
		public DDSE Pickup01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\pickup01.mp3");
		public DDSE Pickup02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\pickup02.mp3");
		public DDSE Pickup03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\pickup03.mp3");
		public DDSE Pickup04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\pickup04.mp3");
		public DDSE Poka01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\poka01.mp3");
		public DDSE Poka02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\poka02.mp3");
		public DDSE Poka03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\poka03.mp3");
		public DDSE ShPickup01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\sh_pickup01.mp3");
		public DDSE ShPickup02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\sh_pickup02.mp3");
		public DDSE ShPickup03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\01pickup\sh_pickup03.mp3");
		public DDSE Laser01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser01.mp3");
		public DDSE Laser02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser02.mp3");
		public DDSE Laser03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser03.mp3");
		public DDSE Laser04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser04.mp3");
		public DDSE Laser05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser05.mp3");
		public DDSE Laser06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser06.mp3");
		public DDSE Laser07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser07.mp3");
		public DDSE Laser08 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\laser08.mp3");
		public DDSE Shoot01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\shoot01.mp3");
		public DDSE Shoot02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\shoot02.mp3");
		public DDSE Shoot03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\shoot03.mp3");
		public DDSE Shoot04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\shoot04.mp3");
		public DDSE Shoot05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\02laser\shoot05.mp3");
		public DDSE Attack01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\attack01.mp3");
		public DDSE Attack02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\attack02.mp3");
		public DDSE Attack03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\attack03.mp3");
		public DDSE Attack04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\attack04.mp3");
		public DDSE Explosion01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion01.mp3");
		public DDSE Explosion02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion02.mp3");
		public DDSE Explosion03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion03.mp3");
		public DDSE Explosion04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion04.mp3");
		public DDSE Explosion05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion05.mp3");
		public DDSE Explosion06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion06.mp3");
		public DDSE Explosion07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion07.mp3");
		public DDSE Explosion08 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion08.mp3");
		public DDSE Explosion09 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\03explosion\explosion09.mp3");
		public DDSE Powerdown01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown01.mp3");
		public DDSE Powerdown02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown02.mp3");
		public DDSE Powerdown03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown03.mp3");
		public DDSE Powerdown04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown04.mp3");
		public DDSE Powerdown05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown05.mp3");
		public DDSE Powerdown06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown06.mp3");
		public DDSE Powerdown07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerdown07.mp3");
		public DDSE Powerup01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup01.mp3");
		public DDSE Powerup02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup02.mp3");
		public DDSE Powerup03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup03.mp3");
		public DDSE Powerup04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup04.mp3");
		public DDSE Powerup05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup05.mp3");
		public DDSE Powerup06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup06.mp3");
		public DDSE Powerup07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup07.mp3");
		public DDSE Powerup08 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup08.mp3");
		public DDSE Powerup09 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup09.mp3");
		public DDSE Powerup10 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\04powerup\powerup10.mp3");
		public DDSE Hit01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit01.mp3");
		public DDSE Hit02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit02.mp3");
		public DDSE Hit03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit03.mp3");
		public DDSE Hit04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit04.mp3");
		public DDSE Hit05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit05.mp3");
		public DDSE Hit06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit06.mp3");
		public DDSE Hit07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\05hit\hit07.mp3");
		public DDSE Jump01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump01.mp3");
		public DDSE Jump02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump02.mp3");
		public DDSE Jump03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump03.mp3");
		public DDSE Jump04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump04.mp3");
		public DDSE Jump05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump05.mp3");
		public DDSE Jump06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump06.mp3");
		public DDSE Jump07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump07.mp3");
		public DDSE Jump08 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump08.mp3");
		public DDSE Jump09 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump09.mp3");
		public DDSE Jump10 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump10.mp3");
		public DDSE Jump11 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump11.mp3");
		public DDSE Jump12 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump12.mp3");
		public DDSE Jump13 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\06jump\jump13.mp3");
		public DDSE Blip01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\blip01.mp3");
		public DDSE Blip02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\blip02.mp3");
		public DDSE Blip03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\blip03.mp3");
		public DDSE Blip04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\blip04.mp3");
		public DDSE Select01 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select01.mp3");
		public DDSE Select02 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select02.mp3");
		public DDSE Select03 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select03.mp3");
		public DDSE Select04 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select04.mp3");
		public DDSE Select05 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select05.mp3");
		public DDSE Select06 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select06.mp3");
		public DDSE Select07 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select07.mp3");
		public DDSE Select08 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select08.mp3");
		public DDSE Select09 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select09.mp3");
		public DDSE Select10 = new DDSE(@"Etoile\G4NovelAdv\小森平\sfxrse\07blip\select10.mp3");
	}
}
