using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Charlotte.Common;

namespace Charlotte
{
	public class ResourceMusic
	{
		//public DDMusic Dummy = new DDMusic("Dummy.mp3");

		public DDMusic Healing01 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing01.mp3");
		public DDMusic Healing02 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing02.mp3");
		public DDMusic Healing03 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing03.mp3");
		public DDMusic Healing04 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing04.mp3");
		public DDMusic Healing05 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing05.mp3");
		public DDMusic Healing06 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing06.mp3");
		public DDMusic Healing07 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing07.mp3");
		public DDMusic Healing08 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing08.mp3");
		public DDMusic Healing09 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing09.mp3");
		public DDMusic Healing10 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing10.mp3");
		public DDMusic Healing11 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing11.mp3");
		public DDMusic Healing11B = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing11b.mp3");
		public DDMusic Healing12 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing12.mp3");
		public DDMusic Healing12B = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing12b.mp3");
		public DDMusic Healing13 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing13.mp3");
		public DDMusic Healing14 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing14.mp3");
		public DDMusic Healing14B = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing14b.mp3");
		public DDMusic Healing15 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing15.mp3");
		public DDMusic Healing16 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing16.mp3");
		public DDMusic Healing17 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_healing\bgm_maoudamashii_healing17.mp3");
		public DDMusic Orchestra01 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra01.mp3");
		public DDMusic Orchestra01B = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra01b.mp3");
		public DDMusic Orchestra02 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra02.mp3");
		public DDMusic Orchestra03 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra03.mp3");
		public DDMusic Orchestra04 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra04.mp3");
		public DDMusic Orchestra05 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra05.mp3");
		public DDMusic Orchestra06 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra06.mp3");
		public DDMusic Orchestra07 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra07.mp3");
		public DDMusic Orchestra08 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra08.mp3");
		public DDMusic Orchestra09 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra09.mp3");
		public DDMusic Orchestra10 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra10.mp3");
		public DDMusic Orchestra11 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra11.mp3");
		public DDMusic Orchestra12 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra12.mp3");
		public DDMusic Orchestra13 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra13.mp3");
		public DDMusic Orchestra14 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra14.mp3");
		public DDMusic Orchestra15 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra15.mp3");
		public DDMusic Orchestra16 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra16.mp3");
		public DDMusic Orchestra17 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra17.mp3");
		public DDMusic Orchestra18 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra18.mp3");
		public DDMusic Orchestra19 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra19.mp3");
		public DDMusic Orchestra20 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra20.mp3");
		public DDMusic Orchestra21 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra21.mp3");
		public DDMusic Orchestra22 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra22.mp3");
		public DDMusic Orchestra23 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra23.mp3");
		public DDMusic Orchestra24 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra24.mp3");
		public DDMusic Orchestra25 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra25.mp3");
		public DDMusic Orchestra26 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_orchestra26.mp3");
		public DDMusic Sinfonia01 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_sinfonia01.mp3");
		public DDMusic Sinfonia01_Piano = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_sinfonia01_piano.mp3");
		public DDMusic Sinfonia02_Piano = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_orchestra\bgm_maoudamashii_sinfonia02_piano.mp3");
		public DDMusic Piano_Ahurera = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano_ahurera.mp3");
		public DDMusic Piano_Calendula = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano_calendula.mp3");
		public DDMusic Piano_FeelsHappiness = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano_feels_happiness.mp3");
		public DDMusic Piano_Milkeyway = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano_milkeyway.mp3");
		public DDMusic Piano_Noapusa = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano_noapusa.mp3");
		public DDMusic Piano_Siroganenokobune = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano_siroganenokobune.mp3");
		public DDMusic Piano01 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano01.mp3");
		public DDMusic Piano02 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano02.mp3");
		public DDMusic Piano03 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano03.mp3");
		public DDMusic Piano04 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano04.mp3");
		public DDMusic Piano05 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano05.mp3");
		public DDMusic Piano06 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano06.mp3");
		public DDMusic Piano07 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano07.mp3");
		public DDMusic Piano08 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano08.mp3");
		public DDMusic Piano09 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano09.mp3");
		public DDMusic Piano10 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano10.mp3");
		public DDMusic Piano11 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano11.mp3");
		public DDMusic Piano12 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano12.mp3");
		public DDMusic Piano13 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano13.mp3");
		public DDMusic Piano14 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano14.mp3");
		public DDMusic Piano15 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano15.mp3");
		public DDMusic Piano16 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano16.mp3");
		public DDMusic Piano17 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano17.mp3");
		public DDMusic Piano18 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano18.mp3");
		public DDMusic Piano19 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano19.mp3");
		public DDMusic Piano20 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano20.mp3");
		public DDMusic Piano21 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano21.mp3");
		public DDMusic Piano22 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano22.mp3");
		public DDMusic Piano23 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano23.mp3");
		public DDMusic Piano24 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano24.mp3");
		public DDMusic Piano25 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano25.mp3");
		public DDMusic Piano26 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano26.mp3");
		public DDMusic Piano27 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano27.mp3");
		public DDMusic Piano28 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano28.mp3");
		public DDMusic Piano29 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano29.mp3");
		public DDMusic Piano30 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano30.mp3");
		public DDMusic Piano31 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano31.mp3");
		public DDMusic Piano32 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano32.mp3");
		public DDMusic Piano33 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano33.mp3");
		public DDMusic Piano34 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano34.mp3");
		public DDMusic Piano35 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano35.mp3");
		public DDMusic Piano36 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano36.mp3");
		public DDMusic Piano37 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano37.mp3");
		public DDMusic Piano38 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano38.mp3");
		public DDMusic Piano39 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano39.mp3");
		public DDMusic Piano40 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano40.mp3");
		public DDMusic Piano41 = new DDMusic(@"Etoile\G4NovelAdv\魔王魂\bgm_maoudamashii_piano\bgm_maoudamashii_piano41.mp3");
	}
}
